## Section 1. Some Julia Tests

In [26]:
x = linspace(0,2*pi,1000);
y = sin(3*x + 4*cos(2*x));
x[1:5]

5-element Array{Float64,1}:
 0.0       
 0.00628947
 0.0125789 
 0.0188684 
 0.0251579 

In [27]:
function is_divisble(n, i)
    return n % i == 0
end

function is_prime(n::Int64)
    if is_divisble(n, 2)
        return false
    end
 
    # initialize a counter variable
    i = 3
 
    while i <= sqrt(n)
        if is_divisble(n, i)
            return false
        end
 
        i += 2
    end
 
    return true
end

is_prime (generic function with 1 method)

In [3]:
is_prime(97)

true

In [4]:
is_prime(1234567)

false

## Gadfly tests

In [31]:
using Gadfly
x=rand(10)
y=rand(10)
plot(x=x,y=y)

0-element Array{Any,1}

### Using some Python related stuff (plotting)

In [7]:
@pyimport numpy as np
tt = np.zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

For example, we can use the Newton solver in scipy.optimize to solve a transcendental equation $cos(x)−x^2=0$ given a Julia function:

In [10]:
@pyimport scipy.optimize as so
so.newton(x -> cos(x) - x^2, 1)

0.8241323123025596

In [23]:
using PyPlot
@pyimport pylab
#pygui()
x = linspace(0,2*pi,1000)
y = sin(3*x + 4*cos(2*x))
plt = pylab.plot(x, y, color="red", linewidth=2.0, linestyle="--")
#ylabel("the y axis")
#xlabel("the x axis")
#title("a sinusoidally-modulated sinusoid")
plt.show()

LoadError: LoadError: type Array has no field show
while loading In[23], in expression starting on line 10